"""initial schema

Revision ID: 7575f34f0330
Revises: 
Create Date: 2026-04-23 10:30:05.473318

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7575f34f0330'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hierarchy_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('level_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['hierarchy_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labor_norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_normalized', sa.String(length=500), nullable=False),
    sa.Column('profession', sa.String(length=300), nullable=True),
    sa.Column('qualification', sa.String(length=300), nullable=True),
    sa.Column('labor_hours', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labor_norms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labor_norms_operation_normalized'), ['operation_normalized'], unique=False)

    op.create_table('normalization_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('replacement', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('conversion_rules', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('equipment_subclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['equipment_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['equipment_classes.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['equipment_subclasses.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('unit_symbol', sa.String(length=50), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['equipment_classes.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['equipment_subclasses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_pattern', sa.String(length=500), nullable=False),
    sa.Column('normalized_pattern', sa.String(length=500), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['equipment_classes.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['equipment_subclasses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_pattern')
    )
    op.create_table('equipment_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hierarchy_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=True),
    sa.Column('model_code', sa.String(length=200), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['equipment_classes.id'], ),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['hierarchy_nodes.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['equipment_subclasses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['equipment_classes.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['equipment_subclasses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apl_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_symbol', sa.String(length=50), nullable=True),
    sa.Column('analog_code', sa.String(length=200), nullable=True),
    sa.Column('analog_name', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_symbol', sa.String(length=50), nullable=True),
    sa.Column('analog_code', sa.String(length=200), nullable=True),
    sa.Column('analog_name', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('runtime_hours', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=True),
    sa.Column('periodicity', sa.String(length=200), nullable=True),
    sa.Column('periodicity_months', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['equipment_classes.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['equipment_subclasses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reliability_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tor_characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tor_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tor_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=500), nullable=True),
    sa.Column('profession', sa.String(length=300), nullable=True),
    sa.Column('qualification', sa.String(length=300), nullable=True),
    sa.Column('labor_hours', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['tor_components.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_tmc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('unit_symbol', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('consumption_rate', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['component_operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_tmc')
    op.drop_table('component_operations')
    op.drop_table('tor_components')
    op.drop_table('tor_characteristics')
    op.drop_table('reliability_metrics')
    op.drop_table('maintenance_types')
    op.drop_table('failure_events')
    op.drop_table('documents')
    op.drop_table('bom_items')
    op.drop_table('apl_items')
    op.drop_table('operations')
    op.drop_table('equipment_models')
    op.drop_table('classification_rules')
    op.drop_table('class_characteristics')
    op.drop_table('characteristics')
    op.drop_table('equipment_subclasses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('qualifications')
    op.drop_table('professions')
    op.drop_table('normalization_rules')
    with op.batch_alter_table('labor_norms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labor_norms_operation_normalized'))

    op.drop_table('labor_norms')
    op.drop_table('hierarchy_nodes')
    op.drop_table('equipment_classes')
    # ### end Alembic commands ###
